### ISSUE TITLE
Cadastrar planejamento falha

### ISSUE THREAD

**Issue by vanhalt** [andersonfernandes/expenses-manager#1]
Quando você está criando planejamento falha porque "category" diz que é repetido:

```bash
já está em uso
```
Somente tenho uma categoria "Transporte". Possível razão [validate uniqueness](https://github.com/andersonfernandes/expenses-manager/blob/master/app/models/planning.rb#L21)

**Comment by andersonfernandes** [comment]
No caso você tentou criar mais de um planejamento por categoria?

**Comment by andersonfernandes** [comment]
Bom, se for o caso que comentei acima está funcionando da maneira que modelei.
